webpack_encore:
    output_path: '%kernel.project_dir%/public/assets'
    script_attributes:
        defer: true

framework:
    assets:
        json_manifest_path: '%kernel.project_dir%/public/assets/manifest.json'
