# define base php-apache image (dev environment)
FROM php:8.5-apache

# set container working directory
WORKDIR /var/www

# install required packages
RUN apt-get update && apt-get install -y \
    libicu-dev \
    rpm
    
# install PHP extensions
RUN docker-php-ext-install pdo_mysql pdo intl

# fix permissions for writing to /var/www (configuration files)
ARG WWWGROUP=1000
ARG WWWUSER=1000
RUN groupmod -o -g ${WWWGROUP} www-data \
    && usermod -o -u ${WWWUSER} www-data
ENV WWWGROUP=${WWWGROUP}
ENV WWWUSER=${WWWUSER}

# copy entrypoint script
COPY ./.docker/docker-entrypoint.sh /usr/local/bin/custom-entrypoint.sh
RUN chmod +x /usr/local/bin/custom-entrypoint.sh

# run entrypoint script
ENTRYPOINT ["custom-entrypoint.sh"]
CMD ["apache2-foreground"]
